### ISSUE TITLE
Why is flush() in Stream and not in Print?

### ISSUE THREAD

**Issue by jandrassy** [arduino/ArduinoCore-API#102]
Why is in Stream.h `virtual void flush() = 0;`?
`flush()` is output related and should be in `Print` as it is in AVR core.

**Comment by matthijskooijman** [comment]
Hm, it surprises me that it is. In the AVR and SAM cores, this method was moved to `Print` a long time ago: https://github.com/arduino/Arduino/pull/2387

I wonder what version this API was based on, or if it was maybe moved back for some reason?

**Comment by PaulStoffregen** [comment]
This repository also seem to *still* pre-date the addition of availableForWrite().  I mentioned this ~2 years ago.  https://github.com/arduino/ArduinoCore-API/issues/64#issuecomment-159860430  Maybe it should be its own issue?  But frankly, I've having a hard time taking this repository seriously.  :(

**Comment by jandrassy** [comment]
> This repository also seem to _still_ pre-date the addition of availableForWrite(), which has been a part of the core library for a very long time. I mentioned this ~4 years ago. [#64 (comment)](https://github.com/arduino/ArduinoCore-API/issues/64#issuecomment-159860430) Maybe it should be its own issue? But frankly, I've having a hard time taking this repository seriously. :(

but it is used in megaavr core and in mbed core

**Comment by bxparks** [comment]
It is even more confusing that:
* the ESP32 core defines `flush()` in its [Stream.h](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Stream.h#L51), while
* the ESP8266 core defines `flush()` in its [Print.h](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Print.h#L103).

I had to use `#if` conditional macros to create code that worked across AVR, ESP8266, ESP32, etc. I would have thought that something as fundamental as `Print` would have a consistent API across all the Arduino platforms.

**Comment by jandrassy** [comment]
https://github.com/espressif/arduino-esp32/issues/943

**Comment by jandrassy** [comment]
> It is even more confusing that:
> 
>     * the ESP32 core defines `flush()` in its [Stream.h](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/Stream.h#L51), while
> 
>     * the ESP8266 core defines `flush()` in its [Print.h](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Print.h#L103).
> 
> 
> I had to use `#if` conditional macros to create code that worked across AVR, ESP8266, ESP32, etc. I would have thought that something as fundamental as `Print` would have a consistent API across all the Arduino platforms.

https://github.com/espressif/arduino-esp32/issues/943

**Comment by jandrassy** [comment]
and in the `namespace arduino` branch for mbed core?

**Comment by facchinm** [comment]
I'm rebasing it there too
