### ISSUE TITLE
Link error undefined reference to attachInterruptParam

### ISSUE THREAD

**Issue by lekgolo167** [arduino/ArduinoCore-API#151]
The file under 

api/Common.h

on line 112 
has a function declaration 
"void attachInterruptParam(pin_size_t interruptNumber, voidFuncPtrParam callback, PinStatus mode, void* param);"

but there are not definitions for this function from what I could find.

**Comment by matthijskooijman** [comment]
IIRC the core that implements this API is expected to implement this function, this repo only provides some convenience wrappers around that function.

**Comment by lekgolo167** [comment]
.

**Comment by lekgolo167** [comment]
Non-issue
