### ISSUE TITLE
Add support for printf, stdio, etc. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/ArduinoCore-API#41]
This is [Issue 903](http://code.google.com/p/arduino/issues/detail?id=903) moved from a Google Code project.
Added by 2012-04-28T07:11:30.000Z by [wes...@gmail.com](http://code.google.com/u/103342639718054305536/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low
### Original description

It might be nice to put an arduino-style wrapper around the standard printf() and related functions.

Serial.setAsSTDOUT();

or something like that.  For anything based on stream ?

**Comment by matthijskooijman** [comment]
This is also requested in #32, so I'm closing this as a duplicate to keep things in one place.
