### ISSUE TITLE
Suggestion to add constants RAND_MAX, AD_MAX, DA_MAX

### ISSUE THREAD

**Issue by btor** [arduino/ArduinoCore-API#47]
To enamble to write portable code please add following costants to a header file:

RAND_MAX -> maximal random number

AD_MAX -> maximal value provided by analogRead() 1023 or 4095 depending on the microcontroller.

Best regards, Bela

**Comment by cmaglie** [comment]
Very old issue but... anyway:

- RAND_MAX is the maximum taken from the `random` function:

```
long random(long) { ...
```
so it's `LONG_MAX`

- AD_MAX: is `1024` for every microcontroller, even if the micro has more bits available on the ADC the Arduino API mandates that the result must scaled down to 1024. If you want more bits you must explicitly set it with `analogWriteResolution(...)`.
