### ISSUE TITLE
Add printf patch to print? 

### ISSUE THREAD

**Issue by JulyJim** [arduino/ArduinoCore-API#53]
Arduino web site documents a patch to add to print ( class ) to implement "semistandard" printf.
Would it be possible to implement this patch permanently in next 1.5.x release? 
With limited debugging tools any help to Serial and others ( LCD?)  would be much appreciated. 

Many thanks for speeding up the compiler, nice work!

**Comment by matthijskooijman** [comment]
This is also requested in #32, so I'm closing this as a duplicate to keep things in one place. It is also not entirely clear what patch this issue refers to.
