### ISSUE TITLE
[Suggestion] Print, Stream and HardwareSerial Serial_ interface classes

### ISSUE THREAD

**Issue by mattbaker-digital** [arduino/ArduinoCore-API#67]
Print, Stream and HardwareSerial should inherit from IPrint, IStream and ISerial interface classes to allow common use of the Serial_ and HarwareSerial objects and allow for new interchangeable classes (based on the interfaces).

**Comment by cmaglie** [comment]
`Print` and `Stream` are actually the base classes to inherit from.

`HardwareSerial` and `Serial_` (very bad choiche for the class name I know... but too late to change now) are already Streams.

I don't remember if it was like that back in Mar 2016, but now it is so I'm closing this issue. Feel free to comment further if I'm missing something.
